openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0
paths:
  /products:
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                userId:
                  type: string
      responses:
        '201':
          description: Product created
        '400':
          description: Bad Request
  /products/{id}:
    get:
      summary: Retrieve product details by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
        '404':
          description: Product not found
  /products/user/{userId}:
    get:
      summary: Retrieve all products created by a specific user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of products
        '404':
          description: User not found
        '500':
          description: Error fetching user details
